package tsec.mac

package object instance {

  /*
  Using Either[Throwable,A] allows us not to worry too much about
  JWS instance of MonadError, since one will be generated by the compiler thanks to cats.
  That said, all operations on the pure interpreter will return a more
  refined instance of MonadError
   */
  type MacErrorM[A] = Either[MacError, A]

}
